name: oi_coach
description: "Apex.OS — Terminal de Desempenho"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  glados: ^1.1.1

flutter:
  uses-material-design: true
